### ISSUE TITLE
UI Bugs - Porting to WinUI 3 Desktop

### ISSUE THREAD

**Issue by ShortDevelopment** [ShortDevelopment/MC-Manager#2]
As the restrictions of the UWP sandbox got bigger I chose to migrate to **WinUI 3 Deskto**p.   
This allows me to have a standard **win32 application** but with the nice WinUI design we all know and love from UWP.   
As WinUI 3 still has some **problems** / bugs / **missing features**, everything that has to do with UI goes here…

**Comment by ShortDevelopment** [comment]
ToolBar (`DRAG_BAR_WINDOW_CLASS`) partially blocks the access to the `NavigationView`   
![image](https://user-images.githubusercontent.com/55882808/151243701-6af4e37b-6667-487e-83ea-46978181d7a6.png)

**Comment by Osaxely** [comment]
Hello, I'm curious about the "got bigger" sentence. What limitations were added?

**Comment by ShortDevelopment** [comment]
Actually I might have expressed my self a little wrong. The restrictions haven’t gotten any worse (Microsoft did not introduce any further restrictions) but rather did my expectations toward the goals of the app hit the limit more often.    
   
For example: I need to access the folder where Minecraft is saving all its game data, but I’m normally not allowed to (at least as a UWP app). You can use `rescap:broadFileSystemAccess` but then users start asking question “why is this needed?!” and you even need to direct them to go to the settings app and search for the right toggle.   
Another problem is sockets. UWP does not allow connections from localhost to a socket so the `WebSocket` tab would not work without entering commands into powershell.   
   
That’s not really a great user experience…

**Comment by Osaxely** [comment]
Make sense. I agree with you. 

As the developer of the app MC Addons Manager (if you know it), I've been encountering a bunch of issues and it was kind of a pain to implement some features.

Moreover these are on Xbox and PC so it needed to adapt the app, lol.

I wish you a great continuation with your app, there is a nice potential.

**Comment by ShortDevelopment** [comment]
@Osaxely 
> As the developer of the app "MC Addons Manager"

I think I've seen it before, but it's not open source, is it?

> I wish you a great continuation with your app, there is a nice potential.

Thanks, I'll try the best I can (besides school).

> `runFullTrust` capability if you'd like to use `broadFileSystemAccess` without asking

That's actually very good to know, thank you!

**Comment by ShortDevelopment** [comment]
@Osaxely
> It is a truly personal choice.

I can totally understand your decision.

> I may contribute to your app if you allow me to, on my free time!

Shure, as I currently got a lot to do for school, it would be great if someone would want to help me and I’m also lacking more ideas… 😀
I also just opened the discussions tab, so we can move out of this issue 🙃
